name: 'Build evmone EVM'
description: 'Builds the evmone EVM binary'
inputs:
  repo:
    description: 'Source repository to use to build the EVM binary'
    required: true
    default: 'ethereum/evmone'
  ref:
    description: 'Reference to branch, commit, or tag to use to build the EVM binary'
    required: true
    default: 'master'
  targets:
    description: 'Which targets to build from evmone repo'
    required: false
    default: 'all'
runs:
  using: "composite"
  steps:
    - name: Get latest evmone commit
      id: evmone-sha
      shell: bash
      run: |
        SHA=$(git ls-remote https://github.com/${{ inputs.repo }}.git refs/heads/${{ inputs.ref }} | cut -f1)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        echo "Latest evmone commit: $SHA"
    - name: Prepare cache target dir
      shell: bash
      run: mkdir -p "$GITHUB_WORKSPACE/evmone/build"
    - name: Restore build cache
      id: cache-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: |
          ${{ github.workspace }}/evmone/build
        key: evmone-build-targets=${{ inputs.targets }}-sha=${{ steps.evmone-sha.outputs.sha }}
        restore-keys: |
          evmone-build-targets=${{ inputs.targets }}-
    - name: Checkout evmone
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ steps.evmone-sha.outputs.sha }}
        path: evmone
        submodules: true
    - name: Setup cmake
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be
      with:
        cmake-version: '3.x'
    - name: "Install GMP Linux"
      if: runner.os == 'Linux' && steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: sudo apt-get -q update && sudo apt-get -qy install libgmp-dev
    - name: Install GMP macOS
      if: runner.os == 'macOS' && steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        brew update && brew install gmp
    - name: Build evmone binary
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        cd $GITHUB_WORKSPACE/evmone
        cmake -S . -B build -DEVMONE_TESTING=ON -DEVMONE_PRECOMPILES_SILKPRE=1
        cmake --build build --parallel --target ${{ inputs.targets }}
    - name: Add evmone bin to PATH
      shell: bash
      run: echo $GITHUB_WORKSPACE/evmone/build/bin/ >> $GITHUB_PATH
    - name: Save build cache
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: |
          ${{ github.workspace }}/evmone/build
        key: evmone-build-targets=${{ inputs.targets }}-sha=${{ steps.evmone-sha.outputs.sha }}
