name: Build Benchmark Genesis Asset
description: Generate benchmark_genesis.tar.gz from benchmark fixtures using Hive
inputs:
  fixtures_path:
    description: "Path to the benchmark fixtures tarball"
    required: true
outputs:
  genesis_tarball:
    description: "Path to the generated benchmark_genesis.tar.gz"
    value: ${{ steps.create-tarball.outputs.path }}
runs:
  using: "composite"
  steps:
    - name: Checkout Hive
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ethereum/hive
        ref: master
        path: hive

    - name: Setup Go for Hive
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ">=1.24"
        cache-dependency-path: hive/go.sum

    - name: Build Hive
      shell: bash
      run: |
        cd hive
        go build .

    - name: Extract benchmark fixtures
      shell: bash
      run: |
        echo "Extracting fixtures from ${{ inputs.fixtures_path }}"
        tar -xzf "${{ inputs.fixtures_path }}"
        echo "Fixtures extracted successfully"

    - name: Start Hive in dev mode
      shell: bash
      run: |
        cd hive
        ./hive --dev \
          --client besu,go-ethereum,nethermind \
          --client-file ../.github/configs/hive/latest_client_releases.yaml \
          --docker.output &

        echo "Waiting for Hive to be ready..."
        for i in {1..30}; do
          if curl -s http://127.0.0.1:3000 > /dev/null 2>&1; then
            echo "Hive is ready!"
            exit 0
          fi
          echo "Waiting... ($i/30)"
          sleep 2
        done
        echo "Hive failed to start within timeout"
        exit 1

    - name: Extract genesis configs from clients
      shell: bash
      env:
        HIVE_SIMULATOR: http://127.0.0.1:3000
      run: |
        echo "Running extract_config for benchmark fixtures..."
        uv run extract_config \
          --fixture fixtures/blockchain_tests_engine_x/pre_alloc/ \
          --output genesis/ \
          --hive-url http://127.0.0.1:3000

        echo "Genesis configs extracted successfully"
        ls -la genesis/

    - name: Create benchmark_genesis.tar.gz
      id: create-tarball
      shell: bash
      run: |
        tar czf benchmark_genesis.tar.gz genesis/
        echo "Created benchmark_genesis.tar.gz"
        ls -lh benchmark_genesis.tar.gz
        echo "path=benchmark_genesis.tar.gz" >> "$GITHUB_OUTPUT"
