name: Build Benchmark Genesis Asset
description: Generate benchmark_genesis.tar.gz from benchmark fixtures using Hive
inputs:
  fixtures_path:
    description: "Path to the benchmark fixtures tarball"
    required: true
outputs:
  genesis_tarball:
    description: "Path to the generated benchmark_genesis.tar.gz"
    value: ${{ steps.create-tarball.outputs.path }}
runs:
  using: "composite"
  steps:
    - name: Checkout Hive
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ethereum/hive
        ref: master
        path: hive

    - name: Setup Go for Hive
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ">=1.24"
        cache-dependency-path: hive/go.sum

    - name: Build Hive
      shell: bash
      run: |
        cd hive
        go build .

    - name: Extract benchmark fixtures
      shell: bash
      run: |
        echo "Extracting fixtures from ${{ inputs.fixtures_path }}"
        tar -xzf "${{ inputs.fixtures_path }}"
        echo "Fixtures extracted successfully"

    - name: Start Hive in dev mode
      id: start-hive
      uses: ./.github/actions/start-hive-dev
      with:
        clients: besu,go-ethereum,nethermind
        client-file: .github/configs/hive/latest.yaml
        hive-path: hive

    - name: Extract genesis configs
      shell: bash
      env:
        HIVE_SIMULATOR: ${{ steps.start-hive.outputs.hive-url }}
      run: |
        echo "Running extract_config for benchmark fixtures..."
        uv run extract_config \
          --fixture fixtures/blockchain_tests_engine_x/pre_alloc/ \
          --output genesis/ \
          --hive-url $HIVE_SIMULATOR

        echo "Genesis configs extracted successfully"
        ls -la genesis/

    - name: Create benchmark_genesis.tar.gz
      id: create-tarball
      shell: bash
      run: |
        tar czf benchmark_genesis.tar.gz genesis/
        echo "Created benchmark_genesis.tar.gz"
        ls -lh benchmark_genesis.tar.gz
        echo "path=benchmark_genesis.tar.gz" >> "$GITHUB_OUTPUT"
